Repository snack-game/server, pull requests merged in 2024-02, with the labels that each got.

#95 refactor: 액세스 토큰을 쿠키로 이관한다
  src/main/java/com/snackgame/server/auth/token/TokenService.java
  src/main/java/com/snackgame/server/auth/token/dto/TokenDto.java
  src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
  src/main/java/com/snackgame/server/member/controller/AuthController.java
  src/test/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolverTest.java
  src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
Labels: infra, refactor

#99 feat: 시즌 제도 도입
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/snackgame/server/applegame/AppleGameService.java
  src/main/java/com/snackgame/server/applegame/domain/game/AppleGame.java
  src/main/java/com/snackgame/server/applegame/domain/game/AppleGames.java
  src/main/java/com/snackgame/server/applegame/exception/NotOwnedException.java
  src/main/java/com/snackgame/server/auth/oauth/config/OAuthConfig.java
  src/main/java/com/snackgame/server/member/controller/dto/NameRequest.java
  src/main/java/com/snackgame/server/rank/applegame/BestScoreRankingService.java
  src/main/java/com/snackgame/server/rank/applegame/config/SeasonsInitializer.java
  src/main/java/com/snackgame/server/rank/applegame/controller/AppleGameRankingController.java
  src/main/java/com/snackgame/server/rank/applegame/domain/AppleGameBestScoreTransfer.java
  src/main/java/com/snackgame/server/rank/applegame/domain/BestScore.java
  src/main/java/com/snackgame/server/rank/applegame/domain/BestScores.java
  src/main/java/com/snackgame/server/rank/applegame/domain/Season.java
  src/main/java/com/snackgame/server/rank/applegame/domain/SeasonRepository.java
  src/main/resources/application-test.yml
  src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java
  src/test/java/com/snackgame/server/applegame/domain/game/AppleGameTest.java
  src/test/java/com/snackgame/server/fixture/BestScoreFixture.java
  src/test/java/com/snackgame/server/fixture/SeasonFixture.java
  src/test/java/com/snackgame/server/member/domain/MemberRepositoryTest.java
  src/test/java/com/snackgame/server/member/fixture/FixtureUtil.java
  src/test/java/com/snackgame/server/member/fixture/GroupFixture.java
  src/test/java/com/snackgame/server/member/fixture/MemberFixture.java
  src/test/java/com/snackgame/server/rank/applegame/BestScoreRankingServiceTest.java
  src/test/java/com/snackgame/server/rank/applegame/controller/AppleGameRankingControllerTest.java
  src/test/java/com/snackgame/server/rank/applegame/dao/SessionRankingDaoTest.java
  src/test/java/com/snackgame/server/rank/applegame/domain/BestScoresTest.java
  src/test/java/com/snackgame/server/support/SecurityIgnoringConfig.java
  src/test/java/com/snackgame/server/support/fixture/EntityOperation.java
  src/test/java/com/snackgame/server/support/fixture/FixtureSaver.java
  src/test/java/com/snackgame/server/support/general/DatabaseCleaningDataJpaTest.java
  src/test/resources/application.yml
Labels: feat

#100 refactor: KeyLocator 제거
  src/main/java/com/snackgame/server/auth/token/util/JwtProvider.java
  src/main/java/com/snackgame/server/auth/token/util/KeyLocator.java
Labels: refactor

#101 fix: 게스트와 소셜 계정 점수 통합 버그 수정
  src/main/java/com/snackgame/server/rank/applegame/domain/AppleGameBestScoreTransfer.java
Labels: fix

#104 feat: 레벨 시스템 도입
  src/main/java/com/snackgame/server/applegame/AppleGameService.java
  src/main/java/com/snackgame/server/applegame/controller/dto/AppleGameResponseV2.java
  src/main/java/com/snackgame/server/member/MemberAccountService.java
  src/main/java/com/snackgame/server/member/controller/AuthController.java
  src/main/java/com/snackgame/server/member/controller/MemberController.java
  src/main/java/com/snackgame/server/member/controller/dto/MemberDetailsResponse.java
  src/main/java/com/snackgame/server/member/controller/dto/StatusResponse.java
  src/main/java/com/snackgame/server/member/domain/Guest.java
  src/main/java/com/snackgame/server/member/domain/Member.java
  src/main/java/com/snackgame/server/member/domain/SnackgameSocialMemberSaver.java
  src/main/java/com/snackgame/server/member/domain/SocialMember.java
  src/main/java/com/snackgame/server/member/domain/Status.java
  src/main/java/com/snackgame/server/rank/applegame/controller/dto/RankingResponse.java
  src/test/java/com/snackgame/server/ServerApplicationTests.java
  src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java
  src/test/java/com/snackgame/server/auth/token/TokenServiceTest.java
  src/test/java/com/snackgame/server/member/MemberAccountServiceTest.java
  src/test/java/com/snackgame/server/member/domain/GuestTest.java
  src/test/java/com/snackgame/server/member/domain/MemberRepositoryTest.java
  src/test/java/com/snackgame/server/member/domain/StatusTest.java
  src/test/java/com/snackgame/server/member/fixture/MemberFixture.java
  src/test/java/com/snackgame/server/rank/applegame/BestScoreRankingServiceTest.java
Labels: feat

#106 feat: 현재 레벨의 최대경험치를 알 수 있다
  src/main/java/com/snackgame/server/member/controller/dto/StatusResponse.java
  src/main/java/com/snackgame/server/member/domain/Status.java
  src/test/java/com/snackgame/server/member/domain/StatusTest.java
Labels: feat

#107 chore: 자동 배포 스크립트 개선
  .github/workflows/cd.yml
Labels: infra

#108 refactor: AWS healthCheck를 위한 ViewController 수정
  src/main/java/com/snackgame/server/config/WebMvcConfig.java
Labels: refactor
