Repository snack-game/server, pull requests merged in 2024-01, with the labels that each got.

#85 feat: 랭킹에서 게스트의 점수 노출을 제거한다
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/com/snackgame/server/rank/applegame/AppleGameRankingService.java
  src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java
  src/test/java/com/snackgame/server/rank/applegame/AppleGameRankingServiceTest.java
Labels: feat

#86 feat: 배포 자동화를 무중단으로 개선한다
  .github/workflows/cd.yml
Labels: feat, infra

#87 feat(deploy): 그린 어플리케이션 실행 검증
  .github/workflows/cd.yml
Labels: feat, infra

#89 refactor: 인증 예외 및 예외 응답 개선
  src/main/java/com/snackgame/server/auth/exception/AuthException.java
  src/main/java/com/snackgame/server/auth/exception/InvalidTokenException.java
  src/main/java/com/snackgame/server/auth/exception/OAuthAuthenticationException.java
  src/main/java/com/snackgame/server/auth/exception/TokenAuthenticationException.java
  src/main/java/com/snackgame/server/auth/exception/TokenExpiredException.java
  src/main/java/com/snackgame/server/auth/exception/TokenInvalidException.java
  src/main/java/com/snackgame/server/auth/exception/TokenUnresolvableException.java
  src/main/java/com/snackgame/server/auth/token/util/JwtProvider.java
  src/main/java/com/snackgame/server/common/exception/GlobalExceptionHandler.java
  src/main/java/com/snackgame/server/common/exception/dto/ExceptionResponse.java
Labels: infra, refactor

#88 feat: 토큰 갱신
  build.gradle
  src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2.java
  src/main/java/com/snackgame/server/auth/exception/AuthException.java
  src/main/java/com/snackgame/server/auth/exception/InvalidTokenException.java
  src/main/java/com/snackgame/server/auth/exception/OAuthAuthenticationException.java
  src/main/java/com/snackgame/server/auth/exception/TokenAuthenticationException.java
  src/main/java/com/snackgame/server/auth/exception/TokenExpiredException.java
  src/main/java/com/snackgame/server/auth/exception/TokenInvalidException.java
  src/main/java/com/snackgame/server/auth/exception/TokenUnresolvableException.java
  src/main/java/com/snackgame/server/auth/token/JwtProviderConfig.java
  src/main/java/com/snackgame/server/auth/token/TokenService.java
  src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
  src/main/java/com/snackgame/server/auth/token/domain/RefreshTokenRepository.java
  src/main/java/com/snackgame/server/auth/token/dto/TokenDto.java
  src/main/java/com/snackgame/server/auth/token/support/Authenticated.java
  src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
  src/main/java/com/snackgame/server/auth/token/support/MemberResolver.java
  src/main/java/com/snackgame/server/auth/token/util/BearerTokenExtractor.java
  src/main/java/com/snackgame/server/auth/token/util/JwtProvider.java
  src/main/java/com/snackgame/server/common/exception/GlobalExceptionHandler.java
  src/main/java/com/snackgame/server/common/exception/dto/ExceptionResponse.java
  src/main/java/com/snackgame/server/config/OpenApiConfig.java
  src/main/java/com/snackgame/server/config/WebMvcConfig.java
  src/main/java/com/snackgame/server/member/controller/AuthController.java
  src/main/java/com/snackgame/server/member/controller/MemberController.java
  src/main/java/com/snackgame/server/member/controller/dto/TokenResponse.java
  src/main/java/com/snackgame/server/member/domain/SnackgameMemberResolver.java
  src/main/java/com/snackgame/server/rank/applegame/controller/AppleGameRankingController.java
  src/main/resources/application-local.yml
  src/main/resources/application-production.yml
  src/main/resources/application-test.yml
  src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
  src/test/resources/application.yml
Labels: feat, infra

#90 fix: 배포 스크립트에 인자를 추가한다
  .github/workflows/cd.yml
Labels: infra, fix

#92 chore: PR 템플릿
  .github/pull_request_template.md
Labels: minor, infra

#91 feat: 로그아웃 API를 추가한다
  src/main/java/com/snackgame/server/auth/token/TokenService.java
  src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
  src/main/java/com/snackgame/server/member/controller/AuthController.java
  src/test/java/com/snackgame/server/auth/token/TokenServiceTest.java
  src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
Labels: feat, refactor

#93 refactor(test): 테스트와 그 기반 코드를 보완한다
  src/main/java/com/snackgame/server/member/MemberService.java
  src/main/java/com/snackgame/server/member/controller/MemberController.java
  src/main/resources/application-test.yml
  src/test/java/com/snackgame/server/applegame/AppleGameServiceTest.java
  src/test/java/com/snackgame/server/applegame/domain/game/AppleGamesTest.java
  src/test/java/com/snackgame/server/auth/token/TokenServiceTest.java
  src/test/java/com/snackgame/server/member/GroupServiceTest.java
  src/test/java/com/snackgame/server/member/MemberServiceTest.java
  src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
  src/test/java/com/snackgame/server/member/domain/MemberRepositoryTest.java
  src/test/java/com/snackgame/server/member/fixture/MemberFixture.java
  src/test/java/com/snackgame/server/rank/applegame/AppleGameRankingServiceTest.java
  src/test/java/com/snackgame/server/rank/applegame/dao/SessionRankingDaoTest.java
  src/test/java/com/snackgame/server/rank/applegame/domain/BestScoresTest.java
  src/test/java/com/snackgame/server/support/database/CleanDatabaseBeforeEach.java
  src/test/java/com/snackgame/server/support/database/DatabaseCleaner.java
  src/test/java/com/snackgame/server/support/database/DatabaseCleaning.java
  src/test/java/com/snackgame/server/support/general/DatabaseCleaningDataJpaTest.java
  src/test/java/com/snackgame/server/support/general/ServiceTest.java
  src/test/java/com/snackgame/server/support/restassured/RestAssuredTest.java
  src/test/java/com/snackgame/server/support/restassured/SetupRestAssuredPort.java
Labels: infra, refactor

#94 chore: 프로덕션의 ddl-auto 설정을 validate로 변경
  src/main/resources/application-production.yml
Labels: minor, infra, refactor
