Repository snack-game/server, pull requests merged in 2024-05, with the labels that each got.

#139 test: 테스트이름 수정
  src/test/java/com/snackgame/server/history/dao/GameHistoryDaoTest.java
Labels: test

#140 refactor: 소셜로그인 세션 저장방식 변경
  build.gradle
Labels: refactor

#141 feat: 점수를 직접 증가시킨다
  src/main/java/com/snackgame/server/applegame/AppleGameService.java
  src/main/java/com/snackgame/server/applegame/controller/AppleGameControllerV2.java
  src/main/java/com/snackgame/server/applegame/domain/game/AppleGame.java
  src/main/java/com/snackgame/server/applegame/exception/ScoreDecreasingException.java
  src/test/java/com/snackgame/server/applegame/domain/game/AppleGameTest.java
Labels: feat
