Repository snack-game/server, pull requests merged in 2024-04, with the labels that each got.

#124 fix(file): 파일 객체의 해시가 아닌 파일 이름의 해시를 이용한다
  src/main/java/com/snackgame/server/common/file/S3FileUploader.kt
Labels: fix

#130 fix: 배포 스크립트의 오류를 수정한다
  .github/workflows/dev-deploy.yml
  .github/workflows/production-deploy.yml
Labels: infra, fix

#132 fix(deploy): 서버 안켜져있는 경우 대응
  .github/workflows/dev-deploy.yml
  .github/workflows/production-deploy.yml
Labels: infra, fix

#133 fix(oauth): 개발 서버에도 OAuth 설정 적용
  src/main/java/com/snackgame/server/auth/oauth/config/OAuthConfig.java
Labels: fix

#137 refactor: 레거시 제거
  src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
  src/main/java/com/snackgame/server/auth/token/util/BearerTokenExtractor.java
  src/main/java/com/snackgame/server/test/TestController.java
Labels: refactor
